services:
  drcv-livetiming:
    build: .
    container_name: drcv-livetiming
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - DELETE_PASSWORD=drcv26!
    volumes:
      - ./data:/app/data
